// Auto-generated by vloc-engine. Do not edit.

/**
 * Representation of a specific geographical location.
 * 
 * **Why**: Needed for all simulation and map operations.
 * We use f64 for high-precision GPS coordinate storage.
 */
export type Coordinates = { lat: number; lng: number; altitude: number | null }
/**
 * Defines a planned path for simulation.
 * 
 * **Why**: Houses the waypoint collection and loop settings required by the Simulator.
 */
export type Route = { waypoints: Coordinates[]; is_loop: boolean }
/**
 * Encapsulates the complete status of the spoofing engine at a point in time.
 * 
 * **Why**: This is the primary data structure synced between Rust and the React UI.
 */
export type SpoofingState = { is_active: boolean; current_location: Coordinates | null; current_speed_kmh: number; remaining_distance_meters: number | null }
/**
 * Core domain errors for the VLoc simulation engine.
 * 
 * **Why**: Centralizes error management to ensure consistent behavior across the
 * engine and provides serialized error states for the frontend.
 */
export type EngineError = 
/**
 * Provided latitude or longitude is out of Earth's physical bounds.
 */
{ type: "InvalidCoordinate"; message: string } | 
/**
 * Speed value is physically impossible or zero.
 */
{ type: "InvalidSpeed" } | 
/**
 * Insufficient waypoints to calculate a path.
 */
{ type: "InvalidRoute" } | 
/**
 * General failure in starting the simulation environment.
 */
{ type: "SimulationFailed"; message: string }

import { invoke } from "@tauri-apps/api/core";

/**
 * Standard IPC Commands available in the VLoc Engine.
 */
export const commands = {
  /** Starts the spoofing simulation. */
  async start_route(route: Route, speed_kmh: number): Promise<void> {
    return await invoke("start_route", { route, speedKmh: speed_kmh });
  },
  /** Stops the active spoofing simulation. */
  async stop_route(): Promise<void> {
    return await invoke("stop_route");
  },
  /** Retrieves the current synchronization state from the engine. */
  async get_current_state(): Promise<SpoofingState> {
    return await invoke("get_current_state");
  }
};
