// This file is auto-generated by Specta (tauri-specta) at build time.
// Do NOT edit this file manually — your changes will be overwritten.
//
// To regenerate, run: cargo build (in apps/desktop-mobile/src-tauri)

export type Coordinates = { lat: number; lng: number; altitude: number | null };
export type Route = { waypoints: Coordinates[]; is_loop: boolean };
export type SpoofingState = {
  is_active: boolean;
  current_location: Coordinates | null;
  current_speed_kmh: number;
  remaining_distance_meters: number | null;
};
